spring.application.name=ingredients
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mini_dish_db}
spring.datasource.username=${DB_USER:mini_dish_db_manager}
spring.datasource.password=${DB_PASSWORD:123456}

logging.level.com.example.ingredients=DEBUG
logging.level.org.springframework.jdbc=DEBUG